import { PlatformColor, StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'
import { DAY_ROW_HEIGHT, MONTH_HEADER_HEIGHT } from './helpers'

// DragPreviewCard has no date column or divider, but its thumbnail + title must land
// in the same spot on screen as they would inside the real row. Width of what it's
// standing in for: dayRowLeft (52) + dayRowDivider's marginHorizontal*2 + width (29).
const DAY_ROW_DATE_AND_DIVIDER_WIDTH = 52 + 29

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loadingOverlay: { position: 'absolute', top: 12, alignSelf: 'center' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  exportBtn: { padding: 4 },
  exportOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'center', alignItems: 'center' },
  list: { flex: 1 },
  // The tab bar and home indicator are already in the scroll view's adjusted content
  // inset via contentInsetAdjustmentBehavior="automatic".
  listContent: { paddingBottom: 16 },
  safeAreaProbe: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  monthRow: {
    height: MONTH_HEADER_HEIGHT,
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
    paddingBottom: 6,
    backgroundColor: colors.background,
  },
  monthRowLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.tertiaryLabel,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  dayRow: {
    height: DAY_ROW_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
    paddingHorizontal: 16,
  },
  dayRowToday: {
    borderLeftWidth: 3,
    borderLeftColor: colors.blue,
    paddingLeft: 13,
  },
  dayRowLeft: {
    width: 52,
    alignItems: 'center',
  },
  dayRowWeekday: {
    fontSize: 11,
    color: colors.tertiaryLabel,
    fontWeight: '500',
    textTransform: 'uppercase',
  },
  dayRowNum: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.label,
    lineHeight: 24,
  },
  dayRowMonth: {
    fontSize: 10,
    color: colors.tertiaryLabel,
  },
  dayRowTextToday: {
    color: colors.blue,
  },
  dayRowDivider: {
    width: 1,
    height: 36,
    backgroundColor: colors.opaqueSeparator,
    marginHorizontal: 14,
  },
  dayRowContent: { flex: 1, marginLeft: 12 },
  dayRowRecipe: {
    fontSize: 16,
    color: colors.label,
    fontWeight: '500',
  },
  dayRowEmpty: {
    fontSize: 13,
    color: colors.opaqueSeparator,
  },
  dayRowThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  dayRowThumbPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
  },
  dayRowDragHandle: {
    marginLeft: 8,
    width: 24,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetBackground: { backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string },
  sheetHandle: { backgroundColor: PlatformColor('systemGray3') as unknown as string },
  plainTextEntry: {
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 12,
    marginTop: 8,
  },
  plainTextInput: {
    flex: 1,
    height: 44,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('separator') as unknown as string,
    paddingHorizontal: 16,
    paddingVertical: 0,
    fontSize: 16,
    lineHeight: 21,
    color: PlatformColor('label') as unknown as string,
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
  },
  plainTextAddButton: {
    minWidth: 56,
    height: 44,
    borderRadius: 999,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.orange,
  },
  plainTextAddButtonDisabled: { opacity: 0.45 },
  plainTextAddButtonText: { fontSize: 16, color: '#ffffff' },
  pickerSearchContainer: {
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 8,
    height: 44,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PlatformColor('separator') as unknown as string,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
  },
  pickerSearch: {
    flex: 1,
    paddingVertical: 0,
    fontSize: 16,
    color: PlatformColor('label') as unknown as string,
  },
  removeButton: {
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PlatformColor('systemRed') as unknown as string,
    alignItems: 'center',
  },
  removeButtonText: { color: PlatformColor('systemRed') as unknown as string, fontWeight: '500', fontSize: 16 },
  pickerList: { flex: 1 },
  pickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PlatformColor('separator') as unknown as string,
  },
  pickerItemThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  pickerItemThumbPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
  },
  pickerItemActive: { backgroundColor: colors.brandLight },
  pickerItemText: { flex: 1, fontSize: 16, color: PlatformColor('label') as unknown as string },
  pickerItemTextActive: { color: colors.brand, fontWeight: '600' },
  pickerEmpty: { flex: 1, padding: 40, alignItems: 'center' },
  pickerEmptyText: { fontSize: 16, color: PlatformColor('secondaryLabel') as unknown as string, textAlign: 'center' },
  dragPreviewCard: {
    position: 'absolute',
    top: 0,
    left: 16,
    right: 16,
    height: DAY_ROW_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingLeft: DAY_ROW_DATE_AND_DIVIDER_WIDTH,
    borderRadius: 12,
    backgroundColor: PlatformColor('secondarySystemBackground') as unknown as string,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  dragPreviewTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    color: colors.label,
  },
  dragPreviewThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    marginRight: 12,
  },
  dragPreviewThumbPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: PlatformColor('systemGray5') as unknown as string,
  },
  dropTargetHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: DAY_ROW_HEIGHT,
    backgroundColor: 'rgba(0, 122, 255, 0.08)',
  },
  todayBtn: {
    position: 'absolute',
    right: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.orange,
  },
  todayBtnText: { color: '#ffffff', fontSize: 16, fontWeight: '600' },
})
